# Generated by Django 3.0.2 on 2020-02-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='private',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='searches',
            name='query',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
