# Generated by Django 3.0.2 on 2020-02-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0003_auto_20200209_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searches',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
