# Generated by Django 3.0.2 on 2020-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0004_auto_20200225_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='query',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
